### PR TITLE
Adds executable permission for gradle wrapper for non-Windows systems

### PR DESCRIPTION
**Pull request by TolkienFan17**
See title. And yes, some may question why it had to be its own PR. And by non-Windows I assume that Windows just ignores the chmod value associated with the file because Windows has its own permission system. Who knows.

### CODE REVIEW

**Review by Kirbitz — COMMENTED** [review]
Going to need more explanation on the purpose of this change.  Are you or anyone else running this project on a system other than windows?

**Comment by TolkienFan17** [comment]
Yes, I came across this issue while trying to setup an development environment on my main computer, which is running Debian Bookworm at the moment.

**Review by Kirbitz — COMMENTED** [review]
Alright, follow up what was changed?  I am comparing the gradlew file on this branch to the one in main and am not seeing any changes

**Comment by TolkienFan17** [comment]
The permission value on the file was changed. I ran `chmod u+x ./gradlew`, and it looks like git translated that into 755 permission value instead. Previously, it had read-write perms only, now it has executable perms.

**Review by Kirbitz — APPROVED** [review]
Sounds good thank you for the explanation

**Review by meyert8034 — APPROVED** [review]
Okay

**Pull request merged**
