### PR TITLE
Updates test database to reflect prod

### PR DESCRIPTION
**Pull request by TolkienFan17**
This PR removes the uniqueness constraint on the index of rules and amendments that previously removed on the production database, thereby updating the test database to be once more simulating prod.

### CODE REVIEW

**Review by PistolRcks — CHANGES_REQUESTED** [review]
Inflicts undue suffering among the masses. Please check your use of the ternary operator.

**Review by AdamLucka — CHANGES_REQUESTED** [review]
This shows you creating a lot of files that are not related to the description attached to this PR. Try to update this branch as it may be GitHub being weird.

**Review by AdamLucka — APPROVED** [review]
sure

**Review by Kirbitz — APPROVED** [review]
Sure

**Pull request merged**
